### ISSUE TITLE
问问

### ISSUE THREAD

**Issue by xiaoheiAh** [ianshi/wifi-camera#1]
我最近也在做这个。看你的Read me里不是很清楚，想问问是可以往服务器传图片还是直接通过服务器控制摄像头开关呢

**Comment by ianshi** [comment]
单片机每隔一段时间会发询问给服务器，服务器如果当前有指令，会回复指令，单片机则会执行指令；单片机也可以主动post照片到服务器上，这个可以不受服务器控制

**Comment by xiaoheiAh** [comment]
你好我想问一下，往服务器传图片的原理是将图片解码成数组然后通过wifi传到服务器，服务器再进行编码吗?那个HTPP协议的资料能借我参考参考吗?最近在做这个项目，想连接到云服务器，但一直找不到HTTP协议的资料，急得要死。万分感谢啊！

**Comment by ianshi** [comment]
1、摄像头是ov2440，支持jpg输出，所以没有涉及编码问题；
2、http的我是从“协议森林”和其他博客了解的，当时没有特别做记录，主要是要攻克http传文件的报文格式问题，你可以参考这个博客。http://blog.csdn.net/devil_2009/article/details/8013356 。也可以直接看代码，我的代码里面有直接对报文进行拼接

**Comment by ianshi** [comment]
更正：摄像头是ov2640。
另外，限于stm32的内存大小和处理速度，还有串口传输速率，图片的质量并不高，而且传输的不是视频流，而是一帧帧的图片，每拍一帧图片上传到服务器，大概需要7-10s的时间，是很慢的

**Comment by xiaoheiAh** [comment]
非常感谢！

2017年5月14日 上午10:43，"ianshi" <notifications@github.com>写道：

**Comment by yisui666** [comment]
请问服务器那边是如何实现接收的
